import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

import { Button } from '@libs/dng-ui/user-actions/Button'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>DeLorean Next Generation</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        {/* <h1>DeLorean Next Generation</h1>
        <Button>CLICK ME</Button> */}
      </div>
    </>
  )
}
